import { Footer } from "@/sections/Footer/Footer";
import { Header } from "@/sections/Home/Header/Header";
import { Intro } from "@/sections/Home/Intro/Intro";
import { Movie } from "@/sections/Home/Movie/Movie";
import { Showcase } from "@/sections/Home/Showcase/Showcase";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black-bg overflow-hidden">
        <div className="container">
          <Header />
          <Intro />
          <Showcase />
          <Showcase />
          <Movie />
          <Footer />
        </div>
      </div>
    </>
  );
}
